### ISSUE TITLE
Use sha512 instead sha256

### ISSUE THREAD

**Issue by im-kulikov** [nspcc-dev/neofs-crypto#4]
```
→ openssl speed sha256 sha512
Doing sha256 for 3s on 16 size blocks: 12225593 sha256's in 3.00s
Doing sha256 for 3s on 64 size blocks: 6553203 sha256's in 3.00s
Doing sha256 for 3s on 256 size blocks: 2741611 sha256's in 3.00s
Doing sha256 for 3s on 1024 size blocks: 821370 sha256's in 3.00s
Doing sha256 for 3s on 8192 size blocks: 110771 sha256's in 3.00s
Doing sha512 for 3s on 16 size blocks: 9471585 sha512's in 3.00s
Doing sha512 for 3s on 64 size blocks: 9334660 sha512's in 3.00s
Doing sha512 for 3s on 256 size blocks: 3437567 sha512's in 3.00s
Doing sha512 for 3s on 1024 size blocks: 1188734 sha512's in 3.00s
Doing sha512 for 3s on 8192 size blocks: 166362 sha512's in 2.98s
LibreSSL 2.8.3
built on: date not available
options:bn(64,64) rc4(16x,int) des(idx,cisc,16,int) aes(partial) blowfish(idx)
compiler: information not available
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
sha256           65216.18k   139699.45k   234138.35k   280340.50k   302395.12k
sha512           50569.85k   199423.79k   293469.94k   405844.91k   457539.13k
```

**Comment by fyrchik** [comment]
What is the motivation?

**Comment by im-kulikov** [comment]
@fyrchik https://www.atraining.ru/sha-2-fastest-sha-512/

> SHA-256 will be more profitable only in the case of a “32-bit server with a 32-bit client” - this scenario can now be considered an endangered exotic.

> SHA-512 will spend a quarter more rounds (80 vs 64) than SHA-256. But each round on the SHA-512 processes 64 bit operands, and on the SHA-256 - 32 bit. Doubled efficiency on operands combined with guaranteed loss of a quarter of speed in additional rounds will give 2 / (5/4) = 1.6 times the advantage. Of course, this is an estimate and there will be additional costs in terms of memory access, bus usage, and so on - but we can say that the SHA-512 on working data volumes will be about 1.5 times faster than the SHA-256.

**Comment by im-kulikov** [comment]
@fyrchik we discussed with @realloc and he proposed to look at SHA512 for hashBytes

**Comment by im-kulikov** [comment]
closed by https://github.com/nspcc-dev/neofs-crypto/pull/7
